### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by joshuacox** [Zayon/kanboard-redmine#1]
cheers on starting this project, my immediate thought on trying it out is to get a docker container up with it inside.  Before going down that route I was wondering if you had already set anything up for this?

**Comment by joshuacox** [comment]
easy place to start would be here: https://hub.docker.com/r/kanboard/kanboard/

**Comment by joshuacox** [comment]
I have a [rancher](http://rancher.com/) template as well that utilizes the above https://github.com/ohmydocker/ohmydocker-catalog/tree/master/templates/kanboard-redmine

**Comment by Zayon** [comment]
Resolved by #2
