### ISSUE TITLE
full circle

### ISSUE THREAD

**Issue by joshuacox** [Zayon/kanboard-redmine#3]
ok, so I've got it running with the [PR](https://github.com/Zayon/kanboard-redmine/pull/2) I put up earlier. I'd like for the Kanboard to update the issue back in redmine.  For example, for bare minimum create a workflow in redmine that mirrors the statuses in kanboard, and when you drag issues in the kanban they ought to move the corresponding 'status' in redmine when it moves in kanboard

**Comment by Zayon** [comment]
Yes, it's in my roadmap

I thought using automatic actions https://kanboard.net/documentation/plugin-automatic-actions

So we could create rules like : When task is dragged into "Done" column, update redmine status to "Resolved"

Is that what you thought about ?

**Comment by Zayon** [comment]
Check out last version to use the new automatic action.
